// App-wide toast notifications — on-brand popups for system messages (login
// errors, "wrong password", saved!, etc.) that slide in from the top. This is
// Hyre's OWN feedback layer, styled in the system colours — nothing to do with
// the browser's native dialogs (Chrome's "password found in a data breach"
// warning is generated by Chrome itself and can't be replaced by a web page).
//
// Usage anywhere under <ToastProvider> (mounted once at the app root):
//   const toast = useToast();
//   toast.error("Invalid email or password.");
//   toast.success("Signed in.");
//   toast.info("Heads up…", { title: "Note", duration: 6000 });
import { createContext, useContext, useCallback, useMemo, useState } from "react";
import { CheckCircle2, AlertTriangle, Info, X } from "lucide-react";

const ToastContext = createContext(null);

// per-type look — icon + accent, drawn on the themed card so it works in light/dark.
const STYLES = {
  error:   { Icon: AlertTriangle, accent: "text-red-600",     bar: "bg-red-600" },
  success: { Icon: CheckCircle2,  accent: "text-green-600",   bar: "bg-green-600" },
  info:    { Icon: Info,          accent: "text-primary",     bar: "bg-primary" },
};

let seq = 0;

export function ToastProvider({ children }) {
  const [toasts, setToasts] = useState([]);

  const dismiss = useCallback((id) => setToasts((list) => list.filter((t) => t.id !== id)), []);

  const push = useCallback((type, message, opts = {}) => {
    const id = ++seq;
    setToasts((list) => [...list, { id, type, message, title: opts.title }]);
    const ttl = opts.duration ?? 4500; // auto-dismiss; pass duration:0 to keep it
    if (ttl) setTimeout(() => dismiss(id), ttl);
    return id;
  }, [dismiss]);

  // Stable API so consumers can depend on it without re-renders.
  const toast = useMemo(() => ({
    error: (m, o) => push("error", m, o),
    success: (m, o) => push("success", m, o),
    info: (m, o) => push("info", m, o),
    dismiss,
  }), [push, dismiss]);

  return (
    <ToastContext.Provider value={toast}>
      {children}
      {/* Toaster — top-centre, above modals (z above the confirm dialog's 100). */}
      <div className="pointer-events-none fixed inset-x-0 top-4 z-[200] flex flex-col items-center gap-2 px-4">
        {toasts.map((t) => {
          const s = STYLES[t.type] || STYLES.info;
          const { Icon } = s;
          return (
            <div
              key={t.id}
              role="status"
              className="pointer-events-auto flex w-full max-w-sm items-start gap-3 overflow-hidden rounded-xl border border-border bg-card p-3.5 shadow-pop animate-in fade-in slide-in-from-top-2"
            >
              <span className={`h-full w-1 shrink-0 self-stretch rounded-full ${s.bar}`} />
              <Icon size={18} className={`mt-0.5 shrink-0 ${s.accent}`} />
              <div className="min-w-0 flex-1">
                {t.title && <p className="text-sm font-bold text-foreground">{t.title}</p>}
                <p className="text-[13px] leading-relaxed text-muted-foreground">{t.message}</p>
              </div>
              <button
                onClick={() => dismiss(t.id)}
                className="shrink-0 rounded-md p-0.5 text-muted-foreground transition-colors hover:text-foreground"
                aria-label="Dismiss"
              >
                <X size={15} />
              </button>
            </div>
          );
        })}
      </div>
    </ToastContext.Provider>
  );
}

// Returns { error, success, info, dismiss }. Throws if used outside the provider.
export function useToast() {
  const ctx = useContext(ToastContext);
  if (!ctx) throw new Error("useToast must be used within a ToastProvider");
  return ctx;
}
